name: Python CI ## workflow name

# Trigger the workflow on push and pull request events
on:
  push: ## event type
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest ## container to run the job
    steps:
      # Step1: Checkout the code from repository 
      - name: Checkout code
        uses: actions/checkout@v3 ## action to checkout the code - triggering an event to run the workflow

      # Step2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4 ## action to setup python environment
        with:
          python-version: '3.8' ## python version to use

      # Step3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ## install dependencies from requirements.txt

      # Step4: Run tests
      - name: Run tests
        run: |
          pytest  ## run tests using pytest
